Various api calls backend
CPEN321-Spottr/spottr pull request #31
Opened 2020-11-07 17:52 UTC by danaharlos

Tagging @jake-wickstrom-lb and @seangarveyubc so that they can see new API call paths:
- GET "https://spottr-be.herokuapp.com/workout/workoutplan/:workoutPlanId" : Returns a workout plan by ID
- GET "https://spottr-be.herokuapp.com/workout/history/:numEntries/:startId?" : Returns most recent workout history, where numEntries is the number of workout history entries you want to receive, and startId is an OPTIONAL parameter of the workout history id to start at. (Zane said this would be a good API for the home screen to show recent workout activity)
  NOTE: if you give a startId that is larger than the amount of id's in the workout history table, an error is returned
             if you give a numEntries that is larger than the amount of entries in the table, all of the entries above startId (or if no 
             startId, then just all of the entries in general) are returned with no error
- GET "https://spottr-be.herokuapp.com/workout/history/workout/muscleGroups" : Returns all muscle groups in muscle group table

Stuff for @zfrantzen :
- You might want to merge your PR before me, and then if I need to add new promises anywhere I can do that
- For the API to return workout plan by ID, you had mentioned in the Issue that I would need to "collect data from the workout_exercise table and put it all together", but looking at your code, I reasoned that I don't. This is because the generateWorkoutPlan engine returns only a workoutPlan object, and just adds entries to the exercise table. Since I'd assume the entries in the exercise table would have already been there from when the workout plan was created, I can just return the workout plan as it is in the workout plan table and that would be equivalent to a call from generateWorkoutPlan. If this is not correct, let me know and we can hop on a call or something so you can explain
- I tested backend for my changes but didn't test through frontend yet. After PR merges I can do this if someone sends me APK (because my android studio sux)
- I refactored the google auth stuff so it's in authService.js now 
- I added another backend test for userCreate so that we could have one complete test suite

2020-11-08 18:36 UTC, zfrantzen requested changes
The `getWorkoutPlanById()` method within `workoutService` needs some more work. Please see the comment there. Other than that, everything else looks great to me!

2020-11-08 18:36 UTC, zfrantzen commented on server/src/service/workoutService.js
> +    getWorkoutPlanById: async function (dbConfig, workoutPlanId){
I think this should probably use the `reassembleWorkoutPlan()` method I added in `workoutService.js`. I believe the purpose of this API is more so that we can retrieve a past workout plan which is formatted the same as when it is generated. We don't want to create any new data with this call. This code will likely look similar to `generateOneUpWorkoutPlan()` without any of the new data generation parts.

2020-11-08 18:36 UTC, zfrantzen commented on server/server.js
>  app.post('/token', cors(), async function (req, res){
Nice! I like that this was cleaned up into the `authService`

2020-11-08 20:34 UTC, danaharlos commented on server/src/service/workoutService.js
> +    getWorkoutPlanById: async function (dbConfig, workoutPlanId){
Fixed this in newest commit, lemme know what you think

2020-11-09 02:00 UTC, zfrantzen approved these changes
Looks good to me!

2020-11-09 02:10 UTC, merged